"""add_device_version

Revision ID: 73196ec538a5
Revises: 90e2206cf539
Create Date: 2026-02-07 19:57:41.171094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73196ec538a5'
down_revision: Union[str, Sequence[str], None] = '90e2206cf539'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("devices", sa.Column("version", sa.Integer(), nullable=False, server_default="1"))
    op.alter_column("devices", "version", server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'version')
    # ### end Alembic commands ###
